#include "report_gen.hpp"
#include "logger.hpp"
#include <fstream>
#include <sstream>
#include <iomanip>

namespace ReportGen {

bool generate_html(const std::string& target, const std::string& path, Database& db) {
    std::ofstream out(path);
    if (!out.is_open()) return false;

    auto history = db.get_history(target);
    auto services = db.get_services(target);
    auto ssl = db.get_ssl(target);
    auto geo = db.get_geoip(target);

    out << "<!DOCTYPE html>\n<html>\n<head>\n";
    out << "<title>Gungnir Report - " << target << "</title>\n";
    out << "<style>\n"
        << "body { font-family: sans-serif; margin: 40px; background: #f4f4f9; color: #333; }\n"
        << "h1 { color: #2c3e50; border-bottom: 2px solid #2c3e50; padding-bottom: 10px; }\n"
        << "h2 { color: #34495e; margin-top: 30px; }\n"
        << "table { width: 100%; border-collapse: collapse; margin-top: 10px; background: #fff; }\n"
        << "th, td { border: 1px solid #ddd; padding: 12px; text-align: left; }\n"
        << "th { background-color: #2c3e50; color: white; }\n"
        << "tr:nth-child(even) { background-color: #f2f2f2; }\n"
        << ".footer { margin-top: 50px; font-size: 0.8em; color: #777; text-align: center; }\n"
        << "</style>\n</head>\n<body>\n";

    out << "<h1>Gungnir OSINT Report</h1>\n";
    out << "<p><strong>Target:</strong> " << target << "</p>\n";

    if (geo.success) {
        out << "<h2>GeoIP Information</h2>\n";
        out << "<table>\n"
            << "<tr><th>Country</th><td>" << geo.country << "</td></tr>\n"
            << "<tr><th>Region</th><td>" << geo.region << "</td></tr>\n"
            << "<tr><th>City</th><td>" << geo.city << "</td></tr>\n"
            << "<tr><th>ISP</th><td>" << geo.isp << "</td></tr>\n"
            << "<tr><th>Coordinates</th><td>" << geo.lat << ", " << geo.lon << "</td></tr>\n"
            << "</table>\n";
    }

    if (ssl.success) {
        out << "<h2>SSL Certificate</h2>\n";
        out << "<table>\n"
            << "<tr><th>Subject</th><td>" << ssl.subject << "</td></tr>\n"
            << "<tr><th>Issuer</th><td>" << ssl.issuer << "</td></tr>\n"
            << "<tr><th>Valid From</th><td>" << ssl.valid_from << "</td></tr>\n"
            << "<tr><th>Valid Until</th><td>" << ssl.valid_until << "</td></tr>\n"
            << "</table>\n";
    }

    out << "<h2>Services</h2>\n";
    if (services.empty()) {
        out << "<p>No service information found.</p>\n";
    } else {
        out << "<table>\n<tr><th>Port</th><th>Proto</th><th>Service</th><th>Product</th><th>Version</th></tr>\n";
        for (const auto& s : services) {
            out << "<tr><td>" << s.port << "</td><td>" << s.protocol << "</td><td>" << s.service 
                << "</td><td>" << s.product << "</td><td>" << s.version << "</td></tr>\n";
        }
        out << "</table>\n";
    }

    out << "<h2>Scan History</h2>\n";
    if (history.empty()) {
        out << "<p>No history found.</p>\n";
    } else {
        out << "<table>\n<tr><th>Date</th><th>Ports found</th></tr>\n";
        for (const auto& h : history) {
            out << "<tr><td>" << h.timestamp << "</td><td>";
            for (size_t i = 0; i < h.ports.size(); ++i) {
                out << h.ports[i] << (i == h.ports.size() - 1 ? "" : ", ");
            }
            out << "</td></tr>\n";
        }
        out << "</table>\n";
    }

    out << "<div class='footer'>Generated by Gungnir OSINT Framework</div>\n";
    out << "</body>\n</html>\n";

    return true;
}

bool generate_json(const std::string& target, const std::string& path, Database& db) {
    std::ofstream out(path);
    if (!out.is_open()) return false;

    auto history = db.get_history(target);
    auto services = db.get_services(target);

    out << "{\n  \"target\": \"" << target << "\",\n";
    
    out << "  \"services\": [\n";
    for (size_t i = 0; i < services.size(); ++i) {
        const auto& s = services[i];
        out << "    {\n"
            << "      \"port\": " << s.port << ",\n"
            << "      \"protocol\": \"" << s.protocol << "\",\n"
            << "      \"service\": \"" << s.service << "\",\n"
            << "      \"product\": \"" << s.product << "\",\n"
            << "      \"version\": \"" << s.version << "\"\n"
            << "    }" << (i == services.size() - 1 ? "" : ",") << "\n";
    }
    out << "  ],\n";

    out << "  \"history\": [\n";
    for (size_t i = 0; i < history.size(); ++i) {
        const auto& h = history[i];
        out << "    {\n"
            << "      \"timestamp\": \"" << h.timestamp << "\",\n"
            << "      \"ports\": [";
        for (size_t j = 0; j < h.ports.size(); ++j) {
            out << h.ports[j] << (j == h.ports.size() - 1 ? "" : ", ");
        }
        out << "]\n    }" << (i == history.size() - 1 ? "" : ",") << "\n";
    }
    out << "  ]\n}\n";

    return true;
}

bool generate(const std::string& target, const std::string& output_path, Format fmt, Database& db) {
    if (fmt == Format::HTML) return generate_html(target, output_path, db);
    return generate_json(target, output_path, db);
}

} // namespace ReportGen
