#include "report_gen.hpp"
#include "logger.hpp"
#include "json.hpp"
#include <fstream>
#include <sstream>
#include <iomanip>

using json = nlohmann::json;

namespace ReportGen {

namespace {

// Escapes the handful of characters that are unsafe to drop verbatim into
// HTML text/attribute context. All target/service/banner strings come from
// scan results (i.e. untrusted input from the network), so this matters —
// without it a malicious banner like "<script>..." would be rendered as-is.
std::string html_escape(const std::string& s) {
    std::string out;
    out.reserve(s.size());
    for (char c : s) {
        switch (c) {
            case '&':  out += "&amp;";  break;
            case '<':  out += "&lt;";   break;
            case '>':  out += "&gt;";   break;
            case '"':  out += "&quot;"; break;
            case '\'': out += "&#39;";  break;
            default:   out += c;        break;
        }
    }
    return out;
}

}  // namespace

bool generate_html(const std::string& target, const std::string& path, Database& db) {
    std::ofstream out(path);
    if (!out.is_open()) return false;

    auto history  = db.get_history(target);
    auto services = db.get_services(target);
    auto ssl       = db.get_ssl(target);
    auto geo       = db.get_geoip(target);

    const std::string target_esc = html_escape(target);

    out << "<!DOCTYPE html>\n<html>\n<head>\n";
    out << "<meta charset=\"utf-8\">\n";
    out << "<title>Gungnir Report - " << target_esc << "</title>\n";
    out << "<style>\n"
        << "body { font-family: sans-serif; margin: 40px; background: #f4f4f9; color: #333; }\n"
        << "h1 { color: #2c3e50; border-bottom: 2px solid #2c3e50; padding-bottom: 10px; }\n"
        << "h2 { color: #34495e; margin-top: 30px; }\n"
        << "table { width: 100%; border-collapse: collapse; margin-top: 10px; background: #fff; }\n"
        << "th, td { border: 1px solid #ddd; padding: 12px; text-align: left; }\n"
        << "th { background-color: #2c3e50; color: white; }\n"
        << "tr:nth-child(even) { background-color: #f2f2f2; }\n"
        << ".footer { margin-top: 50px; font-size: 0.8em; color: #777; text-align: center; }\n"
        << "</style>\n</head>\n<body>\n";

    out << "<h1>Gungnir OSINT Report</h1>\n";
    out << "<p><strong>Target:</strong> " << target_esc << "</p>\n";

    if (geo.success) {
        out << "<h2>GeoIP Information</h2>\n";
        out << "<table>\n"
            << "<tr><th>Country</th><td>" << html_escape(geo.country) << "</td></tr>\n"
            << "<tr><th>Region</th><td>" << html_escape(geo.region) << "</td></tr>\n"
            << "<tr><th>City</th><td>" << html_escape(geo.city) << "</td></tr>\n"
            << "<tr><th>ISP</th><td>" << html_escape(geo.isp) << "</td></tr>\n"
            << "<tr><th>Coordinates</th><td>" << geo.lat << ", " << geo.lon << "</td></tr>\n"
            << "</table>\n";
    }

    if (ssl.success) {
        out << "<h2>SSL Certificate</h2>\n";
        out << "<table>\n"
            << "<tr><th>Subject</th><td>" << html_escape(ssl.subject) << "</td></tr>\n"
            << "<tr><th>Issuer</th><td>" << html_escape(ssl.issuer) << "</td></tr>\n"
            << "<tr><th>Valid From</th><td>" << html_escape(ssl.valid_from) << "</td></tr>\n"
            << "<tr><th>Valid Until</th><td>" << html_escape(ssl.valid_until) << "</td></tr>\n"
            << "</table>\n";
    }

    out << "<h2>Services</h2>\n";
    if (services.empty()) {
        out << "<p>No service information found.</p>\n";
    } else {
        out << "<table>\n<tr><th>Port</th><th>Proto</th><th>Service</th><th>Product</th><th>Version</th><th>CPE</th></tr>\n";
        for (const auto& s : services) {
            out << "<tr><td>" << s.port << "</td><td>" << html_escape(s.protocol) << "</td><td>" << html_escape(s.service)
                << "</td><td>" << html_escape(s.product) << "</td><td>" << html_escape(s.version)
                << "</td><td>" << html_escape(s.cpe) << "</td></tr>\n";
        }
        out << "</table>\n";
    }

    out << "<h2>Scan History</h2>\n";
    if (history.empty()) {
        out << "<p>No history found.</p>\n";
    } else {
        out << "<table>\n<tr><th>Date</th><th>Ports found</th></tr>\n";
        for (const auto& h : history) {
            out << "<tr><td>" << html_escape(h.timestamp) << "</td><td>";
            for (size_t i = 0; i < h.ports.size(); ++i) {
                out << h.ports[i] << (i == h.ports.size() - 1 ? "" : ", ");
            }
            out << "</td></tr>\n";
        }
        out << "</table>\n";
    }

    out << "<div class='footer'>Generated by Gungnir OSINT Framework</div>\n";
    out << "</body>\n</html>\n";

    return true;
}

bool generate_json(const std::string& target, const std::string& path, Database& db) {
    std::ofstream out(path);
    if (!out.is_open()) return false;

    auto history  = db.get_history(target);
    auto services = db.get_services(target);
    auto ssl       = db.get_ssl(target);
    auto geo       = db.get_geoip(target);

    json j;
    j["target"] = target;

    json services_arr = json::array();
    for (const auto& s : services) {
        json se;
        se["port"]     = s.port;
        se["protocol"] = s.protocol;
        se["service"]  = s.service;
        se["product"]  = s.product;
        se["version"]  = s.version;
        se["banner"]   = s.banner;
        se["cpe"]      = s.cpe;
        services_arr.push_back(se);
    }
    j["services"] = services_arr;

    if (ssl.success) {
        j["ssl"] = {
            {"subject",     ssl.subject},
            {"issuer",      ssl.issuer},
            {"valid_from",  ssl.valid_from},
            {"valid_until", ssl.valid_until},
        };
    }

    if (geo.success) {
        j["geoip"] = {
            {"country", geo.country},
            {"region",  geo.region},
            {"city",    geo.city},
            {"isp",     geo.isp},
            {"lat",     geo.lat},
            {"lon",     geo.lon},
        };
    }

    json history_arr = json::array();
    for (const auto& h : history) {
        json he;
        he["timestamp"] = h.timestamp;
        he["ports"]     = h.ports;
        history_arr.push_back(he);
    }
    j["history"] = history_arr;

    out << j.dump(2) << "\n";
    return true;
}

bool generate(const std::string& target, const std::string& output_path, Format fmt, Database& db) {
    if (fmt == Format::HTML) return generate_html(target, output_path, db);
    return generate_json(target, output_path, db);
}

} // namespace ReportGen
